# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: 多看点2

on:
  workflow_dispatch:
  schedule:
    - cron: '*/10 * * * *'
  watch:
     types: started
  repository_dispatch:
     types: _
jobs:
   build:
     runs-on: ubuntu-latest
     if: github.event.repository.owner.id == github.event.sender.id
     steps:
      - name: Checkout
        uses: actions/checkout@v2 
      - name: Use Node.js 12.x
        uses: actions/setup-node@v1
        with:
           node-version: 12.x
      - name: npm install
        run: |
          npm install
      - name: '运行 【多看点2】'
        run: |
          node dkd2.js
        env:
           DKDURL2: ${{ secrets.DKDURL2 }}
           DKDHD2: ${{ secrets.DKDHD2 }}
           DKDBODY2: ${{ secrets.DKDBODY2 }}
           DKDTXURL2: ${{ secrets.DKDTXURL2 }}
           DKDTXHD2: ${{ secrets.DKDTXHD2 }}
           DKDTXBODY2: ${{ secrets.DKDTXBODY2 }}
           TG_BOT_TOKEN: ${{ secrets.TG_BOT_TOKEN }}
           TG_USER_ID: ${{ secrets.TG_USER_ID }}
