# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: 多看点3

on:
  workflow_dispatch:
  schedule:
    - cron: '*/10 * * * *'
  watch:
     types: started
  repository_dispatch:
     types: _
jobs:
   build:
     runs-on: ubuntu-latest
     if: github.event.repository.owner.id == github.event.sender.id
     steps:
      - name: Checkout
        uses: actions/checkout@v2 
      - name: Use Node.js 12.x
        uses: actions/setup-node@v1
        with:
           node-version: 12.x
      - name: npm install
        run: |
          npm install
      - name: '运行 【多看点3】'
        run: |
          node dkd3.js
        env:
           DKDURL3: ${{ secrets.DKDURL3 }}
           DKDHD3: ${{ secrets.DKDHD3 }}
           DKDBODY3: ${{ secrets.DKDBODY3 }}
           DKDTXURL3: ${{ secrets.DKDTXURL3 }}
           DKDTXHD3: ${{ secrets.DKDTXHD3 }}
           DKDTXBODY3: ${{ secrets.DKDTXBODY3 }}
           TG_BOT_TOKEN: ${{ secrets.TG_BOT_TOKEN }}
           TG_USER_ID: ${{ secrets.TG_USER_ID }}
