# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: 抖音极速版

on:
   workflow_dispatch:
   schedule:
     - cron: '*/10 * * * *'
   watch:
     types: started
   repository_dispatch:
     types: _
     
jobs:
   build:
     runs-on: ubuntu-latest
     if: github.event.repository.owner.id == github.event.sender.id
     steps:
      - name: Checkout
        uses: actions/checkout@v2 
        with:
          repository: ZhiYi-N/script
      - name: Use Node.js 12.x
        uses: actions/setup-node@v1
        with:
           node-version: 12.x
      - name: npm install
        run: |
          npm install
      - name: '运行 【抖音极速版】'
        run: |
          node dyjsb.js
        env:
          SIGNHEADER: ${{ secrets.SIGNHEADER }}
          SIGNCOOKIE: ${{ secrets.SIGNCOOKIE }}
          STEPHEADER: ${{ secrets.STEPHEADER }}
          STEPKEY: ${{ secrets.STEPKEY }}
          READHEADER: ${{ secrets.READHEADER }}
          READKEY: ${{ secrets.READKEY }}
          TG_BOT_TOKEN: ${{ secrets.TG_BOT_TOKEN }}
          TG_USER_ID: ${{ secrets.TG_USER_ID }}
