# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: 羊毛赚

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'
  watch:
     types: started
  repository_dispatch:
     types: _
jobs:
   build:
     runs-on: ubuntu-latest
     if: github.event.repository.owner.id == github.event.sender.id
     steps:
      - name: Checkout
        uses: actions/checkout@v2 
      - name: Use Node.js 12.x
        uses: actions/setup-node@v1
        with:
           node-version: 12.x
      - name: npm install
        run: |
          npm install
      - name: '运行 【羊毛赚】'
        run: |
          node ymz.js
        env:
          YMZURL: ${{ secrets.YMZURL }}
          YMZHD: ${{ secrets.YMZHD }}
          YMZBODY: ${{ secrets.YMZBODY }}
          YMZBODY1: ${{ secrets.YMZBODY1 }}
          YMZTXBODY: ${{ secrets.YMZTXBODY }}
          TG_BOT_TOKEN: ${{ secrets.TG_BOT_TOKEN }}
          TG_USER_ID: ${{ secrets.TG_USER_ID }}
